name: 'Admin Suite'
description: "Sets up admin themes, modules, and configuration for an improved Drupal administrative experience."
type: 'drupal-recipe'

install:
  - contextual
  - file
  - layout_builder
  - layout_discovery
  - claro
  - gin
  - gin_toolbar
  - navigation
  - navigation_extra_tools
  - dashboard

config:
  strict: false
  import:
    gin:
      - block.block.gin_breadcrumbs
      - block.block.gin_secondary_local_tasks
      - block.block.gin_content
      - block.block.gin_local_actions
      - block.block.gin_messages
      - block.block.gin_page_title
      - block.block.gin_primary_local_tasks
    navigation:
      - navigation.block_layout
      - navigation.settings
      - system.menu.content
      - system.menu.navigation-user-links
  actions:
    system.theme:
      simpleConfigUpdate:
        admin: gin
    block.block.gin_page_title:
      createIfNotExists:
        theme: gin
        plugin: page_title_block
        settings:
          id: page_title_block
          label: 'Page title'
          label_display: '0'
          provider: core
      setRegion: header
      setStatus: true
    block.block.gin_primary_local_tasks:
      setRegion: header
      setStatus: true
    block.block.gin_admin:
      setStatus: false
    block.block.gin_branding:
      setStatus: false
    block.block.gin_local_tasks:
      setStatus: false
    block.block.gin_tools:
      setStatus: false
