name: 'Admin Suite'
description: "Sets up admin themes, modules, and configuration for an improved Drupal administrative experience."
type: 'drupal-recipe'

install:
  - contextual
  - file
  - layout_builder
  - layout_discovery
  - dashboard
  - claro
  - gin
  - gin_toolbar
  - navigation
  - navigation_extra_tools

config:
  strict: false
  import:
    claro:
      - block.block.claro_breadcrumbs
      - block.block.claro_secondary_local_tasks
      - block.block.claro_content
      - block.block.claro_local_actions
      - block.block.claro_messages
      - block.block.claro_page_title
      - block.block.claro_primary_local_tasks
    gin:
      - block.block.gin_breadcrumbs
      - block.block.gin_secondary_local_tasks
      - block.block.gin_content
      - block.block.gin_local_actions
      - block.block.gin_messages
      - block.block.gin_page_title
      - block.block.gin_primary_local_tasks
    navigation:
      - navigation.block_layout
      - navigation.settings
      - system.menu.content
      - system.menu.navigation-user-links
  actions:
    system.theme:
      simpleConfigUpdate:
        admin: gin
    block.block.claro_branding:
      setStatus: false
    block.block.claro_tools:
      setStatus: false
    block.block.claro_admin:
      setStatus: false
    block.block.claro_local_tasks:
      setStatus: false
    block.block.gin_branding:
      setStatus: false
    block.block.gin_tools:
      setStatus: false
    block.block.gin_admin:
      setStatus: false
    block.block.gin_local_tasks:
      setStatus: false
