name: 'Admin Suite'
description: "Sets up admin themes, modules, and configuration for an improved Drupal administrative experience."
type: 'drupal-recipe'

install:
  - contextual
  - file
  - layout_builder
  - layout_discovery
  - claro
  - gin
  - gin_toolbar
  - navigation
  - navigation_extra_tools

config:
  strict: false
  import:
    gin:
      - block.block.gin_breadcrumbs
      - block.block.gin_secondary_local_tasks
      - block.block.gin_content
      - block.block.gin_local_actions
      - block.block.gin_local_tasks
      - block.block.gin_messages
      - block.block.gin_page_title
      - block.block.gin_primary_local_tasks
      - gin.settings
      - navigation.block_layout
      - navigation.settings
      - system.menu.content
  actions:
    system.theme:
      simpleConfigUpdate:
        admin: gin
